# Generated by Django 6.0.3 on 2026-03-12 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('subscription_status', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=10)),
                ('subscription_expiry', models.DateTimeField(blank=True, null=True)),
                ('downloads_today', models.IntegerField(default=0)),
                ('last_download_reset', models.DateField(auto_now_add=True)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('preferred_program', models.CharField(blank=True, choices=[('regular', 'Regular'), ('distance', 'Distance'), ('extension', 'Extension')], help_text='Regular, Distance, or Extension', max_length=10, null=True)),
                ('preferred_year', models.IntegerField(blank=True, null=True)),
                ('preferred_period', models.IntegerField(blank=True, help_text='1 or 2 for semester students. 1,2,3,4 for distance/term students.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by', to='content.department')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-joined_at'],
            },
        ),
    ]
