# Generated by Django 6.0.3 on 2026-03-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subscriptionplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telebirr_number', models.CharField(default='0912345678', help_text='Telebirr phone number students send payment to', max_length=20)),
                ('telebirr_name', models.CharField(blank=True, help_text='Account name shown to students', max_length=100)),
                ('cbe_account', models.CharField(blank=True, help_text='CBE bank account number (optional)', max_length=50)),
                ('cbe_name', models.CharField(blank=True, help_text='CBE account holder name (optional)', max_length=100)),
                ('payment_instructions', models.TextField(blank=True, help_text='Additional payment instructions shown to students')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
