# Generated by Django 6.0.3 on 2026-04-19 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sitesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='cbe_account',
            field=models.CharField(blank=True, help_text='CBE bank account number (optional).', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cbe_name',
            field=models.CharField(blank=True, help_text='CBE account holder name (optional).', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='payment_instructions',
            field=models.TextField(blank=True, help_text='Additional payment instructions shown to students.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telebirr_name',
            field=models.CharField(blank=True, help_text='Account name shown to students.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telebirr_number',
            field=models.CharField(default='0912345678', help_text='Telebirr phone number students send payment to.', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_period',
            field=models.IntegerField(blank=True, help_text='1 or 2 for semester students. 1,2,3 for distance students.', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_program',
            field=models.CharField(blank=True, choices=[('regular', 'Regular'), ('distance', 'Distance'), ('extension', 'Extension')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='badge',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='SubscriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Auto-generated reference code the student includes in payment.', max_length=20, unique=True)),
                ('payment_method', models.CharField(choices=[('telebirr', 'Telebirr'), ('cbe', 'CBE Bank')], default='telebirr', max_length=10)),
                ('paid_from', models.CharField(blank=True, help_text='Phone number or bank account the student paid from.', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount the student claims to have paid.', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_note', models.TextField(blank=True, help_text='Internal note from admin (reason for rejection, etc.)')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(blank=True, help_text='Admin who approved this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='accounts.subscriptionplan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Subscription Request',
                'verbose_name_plural': 'Subscription Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
