# Generated by Django 6.0.3 on 2026-05-01 08:01

from django.conf import settings
from django.db import migrations, models


def reject_duplicate_pending_requests(apps, schema_editor):
    SubscriptionRequest = apps.get_model('accounts', 'SubscriptionRequest')

    duplicate_student_ids = (
        SubscriptionRequest.objects
        .filter(status='pending')
        .values_list('student_id', flat=True)
        .distinct()
    )

    for student_id in duplicate_student_ids:
        pending_requests = list(
            SubscriptionRequest.objects
            .filter(student_id=student_id, status='pending')
            .order_by('-requested_at', '-id')
            .values_list('id', flat=True)
        )
        if len(pending_requests) <= 1:
            continue

        SubscriptionRequest.objects.filter(id__in=pending_requests[1:]).update(
            status='rejected',
            admin_note='Automatically rejected during migration because a newer pending request exists.',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_sitesettings_cbe_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(reject_duplicate_pending_requests, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='subscriptionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('student',), name='unique_pending_subscription_request_per_student'),
        ),
    ]
