# Generated by Django 6.0.3 on 2026-05-04 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_subscriptionrequest_unique_pending_subscription_request_per_student'),
        ('content', '0011_course_course_active_idx_course_course_code_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['telegram_id'], name='student_telegram_id_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['subscription_status', 'subscription_expiry'], name='student_sub_status_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_active'], name='student_active_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionrequest',
            index=models.Index(fields=['status', 'requested_at'], name='subreq_status_requested_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionrequest',
            index=models.Index(fields=['student', 'status'], name='subreq_student_status_idx'),
        ),
    ]
