# Generated by Django 6.0.3 on 2026-05-06 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student_student_telegram_id_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Message text sent to all students.')),
                ('parse_mode', models.CharField(blank=True, choices=[('', 'Plain text'), ('Markdown', 'Markdown'), ('HTML', 'HTML')], default='', help_text='Telegram formatting mode.', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('total_users', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broadcast Message',
                'verbose_name_plural': 'Broadcast Messages',
                'ordering': ['-sent_at'],
            },
        ),
    ]
