# Generated by Django 6.0.3 on 2026-03-12 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('regular', 'Regular'), ('distance', 'Distance'), ('extension', 'Extension')], max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('year', models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')])),
                ('period_type', models.CharField(choices=[('semester', 'Semester'), ('term', 'Term')], default='semester', help_text='Semester for regular/extension. Term for distance.', max_length=10)),
                ('period', models.IntegerField(choices=[(1, 'Semester I / Term I'), (2, 'Semester II / Term II'), (3, 'Term III'), (4, 'Term IV')], help_text='Regular/Extension: 1 or 2 (Semester I or II). Distance: 1, 2, 3, or 4 (Term I to IV).')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('programs', models.ManyToManyField(blank=True, help_text='Which programs offer this course', related_name='courses', to='content.courseprogram')),
                ('departments', models.ManyToManyField(blank=True, related_name='courses', to='content.department')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['year', 'period', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='resources/%Y/%m/')),
                ('file_type', models.CharField(choices=[('lecture_note', 'Lecture Notes'), ('worksheet', 'Worksheet'), ('past_exam', 'Past Exam'), ('exit_exam', 'Exit Exam')], max_length=20)),
                ('extracted_text', models.TextField(blank=True)),
                ('access_level', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='premium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending — awaiting admin review'), ('published', 'Published — visible to students'), ('rejected', 'Rejected — removed from inbox')], default='pending', max_length=10)),
                ('telegram_message_id', models.BigIntegerField(blank=True, help_text='Original Telegram message ID this file came from', null=True)),
                ('original_caption', models.TextField(blank=True, help_text='Original caption from the Telegram message')),
                ('downloads_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='content.course')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='inbox/%Y/%m/')),
                ('original_filename', models.CharField(max_length=500)),
                ('telegram_message_id', models.BigIntegerField(unique=True)),
                ('telegram_caption', models.TextField(blank=True, help_text='Caption from the original Telegram message')),
                ('posted_date', models.DateTimeField()),
                ('processing_status', models.CharField(choices=[('unprocessed', 'Unprocessed'), ('processing', 'Processing'), ('processed', 'Processed — ready for tagging'), ('failed', 'Failed — processing error')], default='unprocessed', max_length=15)),
                ('extracted_text', models.TextField(blank=True)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_resource', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_source', to='content.resource')),
            ],
            options={
                'verbose_name': 'File Inbox',
                'verbose_name_plural': 'File Inbox',
                'ordering': ['-posted_date'],
            },
        ),
    ]
