# Generated by Django 6.0.3 on 2026-03-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_department_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['level', 'name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AddField(
            model_name='department',
            name='level',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate')], default='undergraduate', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
