# Generated by Django 6.0.3 on 2026-03-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_department_options_department_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='period',
            field=models.IntegerField(choices=[(1, 'Semester I / Term I'), (2, 'Semester II / Term II'), (3, 'Term III')], help_text='Regular/Extension: 1 or 2 (Semester I or II). Distance: 1, 2, or 3 (Term I to III).'),
        ),
    ]
