# Generated by Django 6.0.3 on 2026-03-28 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_course_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='course',
            name='period',
        ),
        migrations.RemoveField(
            model_name='course',
            name='period_type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='programs',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
        migrations.CreateModel(
            name='CoursePlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')])),
                ('period_type', models.CharField(choices=[('semester', 'Semester'), ('term', 'Term')], max_length=10)),
                ('period', models.IntegerField(choices=[(1, 'Semester I / Term I'), (2, 'Semester II / Term II'), (3, 'Term III')])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='content.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_placements', to='content.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_placements', to='content.courseprogram')),
            ],
            options={
                'verbose_name': 'Course Placement',
                'verbose_name_plural': 'Course Placements',
                'ordering': ['year', 'period', 'course__name'],
                'unique_together': {('course', 'department', 'program', 'year', 'period')},
            },
        ),
        migrations.AlterField(
            model_name='resource',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='content.courseplacement'),
        ),
    ]
