# Generated by Django 6.0.3 on 2026-03-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_course_options_remove_course_departments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseplacement',
            name='program',
            field=models.CharField(choices=[('regular', 'Regular'), ('distance', 'Distance'), ('extension', 'Extension')], max_length=10),
        ),
        migrations.DeleteModel(
            name='CourseProgram',
        ),
    ]
