# Generated by Django 6.0.3 on 2026-03-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_resource_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseplacement',
            name='period_type',
        ),
    ]
