# Generated by Django 6.0.3 on 2026-04-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_remove_courseplacement_period_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file_type',
            field=models.CharField(choices=[('lecture_note', 'Lecture Notes'), ('module', 'Course Module'), ('worksheet', 'Worksheet')], max_length=20),
        ),
    ]
