# Generated by Codex on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_resource_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinbox',
            name='file',
            field=models.FileField(blank=True, upload_to='inbox/%Y/%m/'),
        ),
    ]
