# Generated by Django 6.0.3 on 2026-05-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_fileinbox_file'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='course_active_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='course_code_idx'),
        ),
        migrations.AddIndex(
            model_name='courseplacement',
            index=models.Index(fields=['department', 'program', 'year', 'period'], name='placement_dept_prog_year_period_idx'),
        ),
        migrations.AddIndex(
            model_name='courseplacement',
            index=models.Index(fields=['course', 'program'], name='placement_course_prog_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active'], name='dept_active_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['level', 'is_active'], name='dept_level_active_idx'),
        ),
        migrations.AddIndex(
            model_name='fileinbox',
            index=models.Index(fields=['assigned_resource', 'processing_status'], name='inbox_assigned_status_idx'),
        ),
        migrations.AddIndex(
            model_name='fileinbox',
            index=models.Index(fields=['telegram_message_id'], name='inbox_telegram_msg_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['course', 'status', 'access_level'], name='resource_course_status_access_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['status', 'created_at'], name='resource_status_created_idx'),
        ),
    ]
