# Generated by Django 6.0.3 on 2026-05-04 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_course_course_active_idx_course_course_code_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='courseplacement',
            new_name='placement_dept_prog_yr_pd_idx',
            old_name='placement_dept_prog_year_period_idx',
        ),
        migrations.RenameIndex(
            model_name='resource',
            new_name='resource_course_status_acc_idx',
            old_name='resource_course_status_access_idx',
        ),
    ]
