# Generated by Django 6.0.3 on 2026-05-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_rename_placement_dept_prog_year_period_idx_placement_dept_prog_yr_pd_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='source',
            field=models.CharField(choices=[('official', 'Official University Material'), ('textbook', 'Recommended Textbook'), ('reference', 'Reference / Internet Resource'), ('notes', 'Lecture Notes / Student Notes'), ('other', 'Other Resource')], default='other', help_text='Where this resource came from. Shown to students as a badge.', max_length=15),
        ),
    ]
