# Generated by Django 6.0.3 on 2026-03-12 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('exam_type', models.CharField(choices=[('final', 'Final Exam'), ('exit', 'Exit Exam')], max_length=10)),
                ('year', models.IntegerField()),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Exam duration in minutes. Fill in after reviewing the paper.', null=True)),
                ('instructions', models.TextField(blank=True, help_text='Official exam instructions shown to students before simulation starts.')),
                ('access_level', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='premium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='content.course')),
                ('source_resource', models.ForeignKey(blank=True, help_text='The original resource file this exam was extracted from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_papers', to='content.resource')),
            ],
            options={
                'verbose_name': 'Exam Paper',
                'verbose_name_plural': 'Exam Papers',
                'ordering': ['-year'],
                'unique_together': {('course', 'exam_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('option_e', models.CharField(blank=True, help_text='Optional 5th choice — only used if exam paper has 5 options', max_length=500)),
                ('correct_option', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], help_text='Leave blank if correct answer is not yet confirmed', max_length=1)),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown to students after answering in practice mode')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('year_source', models.CharField(blank=True, help_text='Year this question appeared e.g. 2022', max_length=10)),
                ('topic_tags', models.JSONField(blank=True, default=list, help_text='Topics this question covers e.g. ["Data Structures", "OOP"]')),
                ('access_level', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='premium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.course')),
                ('exam_paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='quiz.exampaper')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['exam_paper', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('answers', models.JSONField(default=dict, help_text='Format: {question_id: selected_option} e.g. {"12": "a", "13": "c"}')),
                ('mode', models.CharField(choices=[('practice', 'Practice'), ('simulation', 'Simulation'), ('topic', 'Topic')], default='practice', max_length=15)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_attempts', to='content.course')),
                ('exam_paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='quiz.exampaper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'ordering': ['-completed_at'],
            },
        ),
    ]
