# Generated by Django 6.0.3 on 2026-04-18 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_resource_file_type'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exampaper',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Required for Exit Exams. Leave blank for Final Exam and Team Quiz.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_papers', to='content.department'),
        ),
        migrations.AddField(
            model_name='question',
            name='department',
            field=models.ForeignKey(blank=True, help_text='For exit exam questions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='content.department'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_attempts', to='content.department'),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Required for Final Exam and Team Quiz. Leave blank for Exit Exams.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_papers', to='content.course'),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='exam_type',
            field=models.CharField(choices=[('final', 'Final Exam'), ('exit_real', 'Exit Exam — Official'), ('exit_model', 'Exit Exam — Model'), ('quiz', 'Team Quiz')], max_length=15),
        ),
        migrations.AlterField(
            model_name='question',
            name='course',
            field=models.ForeignKey(blank=True, help_text='For final exam and team quiz questions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='content.course'),
        ),
        migrations.AlterUniqueTogether(
            name='exampaper',
            unique_together={('course', 'department', 'exam_type', 'year')},
        ),
    ]
