# Generated by Django 6.0.3 on 2026-04-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_exampaper_unique_together_exampaper_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True / False'), ('fill_blank', 'Fill in the Blank'), ('matching', 'Matching'), ('essay', 'Essay / Short Answer')], default='mcq', help_text='MCQ: options A–E with correct_option. True/False: option_a=True, option_b=False. Fill blank: correct_option holds the answer text. Matching: each option is a "Term → Answer" pair. Essay: no options, open-ended answer.', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(blank=True, help_text='MCQ/True-False: single letter a–e. Fill blank: the correct answer text. Matching/Essay: leave blank.', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_e',
            field=models.CharField(blank=True, help_text='5th MCQ option, or leave blank for other types.', max_length=500),
        ),
    ]
