# Generated by Django 6.0.3 on 2026-04-18 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_resource_file_type'),
        ('quiz', '0003_question_question_type_alter_question_correct_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='access_level',
        ),
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
        migrations.RemoveField(
            model_name='question',
            name='department',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='department',
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='source_resource',
            field=models.ForeignKey(blank=True, help_text='The original resource file this exam was extracted from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_papers', to='content.resource'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam_paper',
            field=models.ForeignKey(blank=True, help_text='Every question must be assigned to an exam paper.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='quiz.exampaper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation shown to students after answering in practice mode.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_e',
            field=models.CharField(blank=True, help_text='5th MCQ option only. Leave blank for other question types.', max_length=500),
        ),
    ]
