# Generated by Django 6.0.3 on 2026-04-18 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_resource_file_type'),
        ('quiz', '0004_remove_question_access_level_remove_question_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='course',
            field=models.ForeignKey(blank=True, help_text='For team quiz attempts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_attempts', to='content.course'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='department',
            field=models.ForeignKey(blank=True, help_text='For department-level quiz attempts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_attempts', to='content.department'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='exam_paper',
            field=models.ForeignKey(blank=True, help_text='For exit exam and final exam attempts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='quiz.exampaper'),
        ),
    ]
