# Generated by Django 6.0.3 on 2026-05-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizattempt_course_quizattempt_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='detailed_answers',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed per-question answer feedback keyed by question id. Includes selected answer, correct answer, options, explanation, topic tags, and correctness metadata.'),
        ),
    ]
