# Generated by Django 6.0.3 on 2026-05-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quizattempt_detailed_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='selected_topics',
            field=models.JSONField(blank=True, default=list, help_text='Topics selected for this attempt e.g. ["Chapter 1", "Loops"]'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='mode',
            field=models.CharField(choices=[('practice', 'Practice'), ('simulation', 'Simulation'), ('topic', 'Topic'), ('selective', 'Selective Practice')], default='practice', max_length=15),
        ),
    ]
