# Generated by Django 6.0.3 on 2026-05-19 10:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_resource_courses_m2m'),
        ('quiz', '0007_quizattempt_selected_topics_alter_quizattempt_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic_tags',
            field=models.JSONField(blank=True, default=list, help_text='Granular topics, not chapters. E.g. ["arrays", "sorting"]'),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Chapter number within course (1, 2, 3...)', validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(help_text='e.g., "Introduction to Entrepreneurship"', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Learning objectives or summary of chapter', null=True)),
                ('icon', models.CharField(blank=True, help_text='Optional emoji or icon, e.g., "📚"', max_length=10, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within course')),
                ('is_active', models.BooleanField(default=True, help_text='Active chapters are shown to students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Which course this chapter belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='content.course')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'ordering': ['course', 'order', 'number'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(blank=True, help_text='Which chapter this question belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='quiz.chapter'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['course', 'is_active'], name='chapter_course_active_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['course', 'number'], name='chapter_course_number_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('course', 'number')},
        ),
    ]
