# Generated by Django 6.0.3 on 2026-10-08 19:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_subscriptionrequest_payment_reference'),
        ('quiz', '0008_alter_question_topic_tags_chapter_question_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='gradable_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='pending_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='QuizSimulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_snapshot', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.quizattempt')),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.exampaper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'exam_paper', 'expires_at'], name='simulation_student_paper_idx')],
            },
        ),
    ]
