# Generated by Django 6.0.3 on 2026-05-11 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=300)),
                ('course_code', models.CharField(max_length=30)),
                ('total_students', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['course_name'],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.IntegerField(help_text='1=Session I, 2=Session II etc.')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(help_text='e.g. K-1, J-5', max_length=20)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='exams.examschedule')),
            ],
        ),
        migrations.AddField(
            model_name='examschedule',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='exams.examsession'),
        ),
        migrations.CreateModel(
            name='ExamTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Ethiopian calendar year e.g. 2018')),
                ('term', models.IntegerField(choices=[(1, 'Term I'), (2, 'Term II'), (3, 'Term III')])),
                ('center', models.CharField(default='Addis Ababa', max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Only one term should be active at a time — this is what students see')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-term'],
                'unique_together': {('year', 'term', 'center')},
            },
        ),
        migrations.AddField(
            model_name='examsession',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exams.examterm'),
        ),
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('course_name', models.CharField(max_length=300)),
                ('course_code', models.CharField(max_length=30)),
                ('room_code', models.CharField(max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exams', to='exams.examsession')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exams', to='exams.examterm')),
            ],
            options={
                'ordering': ['session__date', 'session__start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['course_code'], name='exam_schedule_code_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examsession',
            unique_together={('term', 'session_number', 'date')},
        ),
        migrations.AddIndex(
            model_name='studentexam',
            index=models.Index(fields=['term', 'student_id'], name='student_exam_term_id_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexam',
            index=models.Index(fields=['term', 'student_name'], name='student_exam_term_name_idx'),
        ),
    ]
