# Generated by Django 6.0.3 on 2026-05-11 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before', models.IntegerField(choices=[(15, '15 days before'), (7, '7 days before'), (3, '3 days before')])),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExamPDFUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_type', models.CharField(choices=[('schedule', 'Schedule PDF (1 per term)'), ('attendance', 'Attendance PDF (1 per course/room)')], max_length=15)),
                ('file', models.FileField(upload_to='exam_pdfs/%Y/%m/')),
                ('original_name', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('records_created', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=300)),
                ('course_code', models.CharField(max_length=30)),
                ('total_students', models.IntegerField(default=0)),
                ('rooms', models.CharField(blank=True, help_text='e.g. K-1, K-2, K-3', max_length=100)),
            ],
            options={
                'ordering': ['course_name'],
            },
        ),
        migrations.RemoveField(
            model_name='examroom',
            name='schedule',
        ),
        migrations.RemoveIndex(
            model_name='examschedule',
            name='exam_schedule_code_idx',
        ),
        migrations.AlterModelOptions(
            name='studentexam',
            options={'ordering': ['session__date', 'session__start_time', 'student_name']},
        ),
        migrations.RenameIndex(
            model_name='studentexam',
            new_name='student_exam_id_idx',
            old_name='student_exam_term_id_idx',
        ),
        migrations.RenameIndex(
            model_name='studentexam',
            new_name='student_exam_name_idx',
            old_name='student_exam_term_name_idx',
        ),
        migrations.AddField(
            model_name='examterm',
            name='exam_start_date',
            field=models.DateField(blank=True, help_text='First exam date — used for notification scheduling', null=True),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='session_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='examterm',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Only one term should be active at a time.'),
        ),
        migrations.AddField(
            model_name='examnotificationlog',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='exams.examterm'),
        ),
        migrations.AddField(
            model_name='exampdfupload',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_uploads', to='exams.examterm'),
        ),
        migrations.AddField(
            model_name='examscheduleentry',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='exams.examsession'),
        ),
        migrations.DeleteModel(
            name='ExamRoom',
        ),
        migrations.AlterUniqueTogether(
            name='examnotificationlog',
            unique_together={('term', 'days_before')},
        ),
        migrations.DeleteModel(
            name='ExamSchedule',
        ),
    ]
