# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examnotificationlog_exampdfupload_examscheduleentry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampdfupload',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('processing', 'Processing'),
                    ('processed', 'Processed'),
                    ('failed', 'Failed'),
                ],
                default='pending',
                max_length=15,
            ),
        ),
    ]
