# Generated by Django 6.0.3 on 2026-05-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_add_exam_pdf_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampdfupload',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
